global using UserModel = SubsTracker.DAL.Models.User.User;
global using Group = SubsTracker.DAL.Models.User.UserGroup;
global using SubscriptionModel = SubsTracker.DAL.Models.Subscription.Subscription;
global using System.Net.Http.Json;
global using Newtonsoft.Json;
global using Shouldly;
global using Microsoft.Extensions.DependencyInjection;
global using SubsTracker.API.ViewModel.Subscription;
global using SubsTracker.DAL;
global using SubsTracker.IntegrationTests.Constants;
global using SubsTracker.BLL.DTOs.Subscription;
global using AutoFixture;
global using SubsTracker.Domain.Enums;
global using Microsoft.AspNetCore.Mvc.Testing;
global using Microsoft.EntityFrameworkCore;
global using SubsTracker.IntegrationTests.DataSeedEntities;
global using SubsTracker.DAL.Models.User;
global using SubsTracker.IntegrationTests.Helpers.Subscription;
global using SubsTracker.API.ViewModel.User;
global using SubsTracker.IntegrationTests.Helpers.UserGroup;
global using SubsTracker.BLL.DTOs.User.Create;
global using SubsTracker.BLL.DTOs.User.Update;
global using Microsoft.AspNetCore.Hosting;
global using SubsTracker.API;
