services:
  susb:
    image: susb
    build:
      context: .
      dockerfile: Susb/Dockerfile

  substracker.api:
    image: substracker.api
    build:
      context: .
      dockerfile: SubsTracker.API/Dockerfile
