global using UserModel = SubsTracker.DAL.Entities.UserEntity;
global using Group = SubsTracker.DAL.Entities.GroupEntity;
global using SubscriptionModel = SubsTracker.DAL.Entities.SubscriptionEntity;
global using System.Net.Http.Json;
global using Newtonsoft.Json;
global using Shouldly;
global using Microsoft.Extensions.DependencyInjection;
global using SubsTracker.DAL;
global using SubsTracker.IntegrationTests.Constants;
global using SubsTracker.BLL.DTOs.Subscription;
global using AutoFixture;
global using SubsTracker.Domain.Enums;
global using Microsoft.AspNetCore.Mvc.Testing;
global using Microsoft.EntityFrameworkCore;
global using SubsTracker.IntegrationTests.DataSeedEntities;
global using SubsTracker.IntegrationTests.Helpers.Subscription;
global using SubsTracker.IntegrationTests.Helpers.UserGroup;
global using SubsTracker.BLL.DTOs.User.Create;
global using SubsTracker.BLL.DTOs.User.Update;
global using Microsoft.AspNetCore.Hosting;
global using SubsTracker.API;
global using MassTransit;
global using Microsoft.AspNetCore.Authentication;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using System.Security.Claims;
global using System.Text.Encodings.Web;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using AutoMapper;
global using Microsoft.Extensions.Configuration;
global using SubsTracker.Domain.Options;
global using System.Diagnostics;
global using NSubstitute;
